### ISSUE TITLE
Tests are run multiple times on file change when using a docker volume on OSX

### ISSUE THREAD

**Issue by kenan-rhoton** [jakemcc/lein-test-refresh#76]
**What version of lein-test-refresh?** Version "0.22.0"

**What version of Leiningen?** Leiningen 2.8.1 on Java 1.8.0_151 OpenJDK 64-Bit Server VM

**Can you recreate the issue with a minimal project?** `lein new test` then add the `lein-test-refresh` plugin.

Run with `docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app clojure lein test-refresh`

**Other details:**

The issue seems to be with the number of inotify events triggered within docker on a file change, while inside docker you get the following triggers (on the clojure container runnint `inotifywait -m -r .`:

```
./test/test/ ATTRIB core_test.clj
./test/test/ MODIFY core_test.clj
./test/test/ CREATE core_test.clj~
./test/test/ ATTRIB core_test.clj~
./test/test/ MODIFY core_test.clj~
./test/test/ DELETE core_test.clj~
```

And meanwhile, outside, we only get these (on OSX checked with `fswatch -v .`):
```
/Users/krhoton/testdir/scratch/test-refresh/test/test/test/core_test.clj
/Users/krhoton/testdir/scratch/test-refresh/test/test/test/core_test.clj~
```

I believe in the former case for whatever reason, all events except `DELETE` are triggering the test runner, while the expected case would be for it to ignore all except the `MODIFY` on the `core_test.clj` (ignoring all the `core_test.clk~` events and any `ATTRIB` events).

This conceptually seems like a very simple change, but I don't believe I'm understanding exactly where these events are monitored in the codebase, otherwise I would offer a pull request myself (and I'm willing to, if directed a little bit on where to look).

**Comment by jakemcc** [comment]
Thanks for the detailed issue.

> but I don't believe I'm understanding exactly where these events are monitored in the codebase, otherwise I would offer a pull request myself (and I'm willing to, if directed a little bit on where to look).

Yeah, it is going to be hard to find because it really just polls the file system [loop here](https://github.com/jakemcc/lein-test-refresh/blob/master/test-refresh/src/com/jakemccrary/test_refresh.clj#L252-L297). lein-test-refresh (well, lein-autoexpect which lein-test-refresh was forked from) was written before Java 7 and the DirectoryWatcher class became a thing and I wasn't super satisfied with the other options at the time. Then I wanted to continue supporting Java 6 for a while and never made the transition.

If you'd like to try implementing that and seeing if it makes it better, It is something I've been meaning to try out.
